event:
  url: 'https://event.misw.jp/c101/'
  image: 'images/og.webp'

join:
  url: 'https://twitter.com/misw_info/status/1638361049505353728'
  image: 'img/join-schedule.webp'

blog:
  url: 'https://blog.misw.jp/'

works:
  url: 'https://18dafcde6bdc7f4f399fe8197dd30da9.misw.jp/#works-frame'

jquery:
  url: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js'

overview:
  a:
    name: '設立'
    data: '1969年4月16日'
  b:
    name: '部員数(2023年3月時点)'
    data: '90人 (内インカレ15人)'
  c:
    name: '活動時間'
    data: '木曜日: 17:00～19:00<br />土曜日: 14:00～16:00'
  d:
    name: '活動場所'
    data: '木曜日: 早稲田大学 西早稲田キャンパス 52号館 302教室<br />土曜日: MIS.W公式Discordサーバーでのオンライン活動'
  e:
    name: '部室'
    data: '早稲田大学 戸山キャンパス 学生会館 E927'
  f:
    name: '会費(半期)'
    a:
      name: '新規入会'
      data: '1,500円'
    b:
      name: '継続会員'
      data: '3,000円'

kanbu:
  a:
    role: '幹事長'
    name: 'たまかけ'
    group: 'プロ研'
    image: 'img/kanbu/0.webp'
  b:
    role: '副幹事長'
    name: 'せいる'
    group: 'MIDI研'
    image: 'img/kanbu/1.webp'
  c:
    role: '会計'
    name: 'Polar'
    group: 'プロ研'
    image: 'img/kanbu/2.webp'
  d:
    role: 'プログラミング研会長'
    name: '文月まぐ'
    group: 'プロ研'
    image: 'img/kanbu/3.webp'
  e:
    role: 'CG研会長'
    name: 'NOAH'
    group: 'CG研'
    image: 'img/kanbu/4.webp'
  f:
    role: 'MIDI研会長'
    name: '9W3R7Y'
    group: 'MIDI研'
    image: 'img/kanbu/5.webp'

footer:
  contact: 'メールアドレス: misw.info☆gmail.com(☆を@に直して送信してください)<br />Twitter(<a href="https://twitter.com/misw_info" target="_blank" rel="noopener noreferrer">@misw_info</a>)のダイレクトメッセージにお送りいただくこともできます。'
  copyright: 'Copyright (c) 2018-2023, MIS.W（早稲田大学経営情報学会）All rights reserved.'
