kanbu:
  a:
    role: '幹事長'
    name: 'S-moto'
    group: 'MIDI研'
    image: 'img/kanbu/0.jpg'
  b:
    role: '副幹事長'
    name: 'あんび'
    group: 'CG研'
    image: 'img/kanbu/1.jpg'
  c:
    role: '会計'
    name: 'ななしろ'
    group: 'プロ研'
    image: 'img/kanbu/2.jpg'
  d:
    role: 'プログラミング研会長'
    name: 'T_SUM_U'
    group: 'プロ研'
    image: 'img/kanbu/3.jpg'
  e:
    role: 'CG研会長'
    name: 'ユチェ'
    group: 'CG研'
    image: 'img/kanbu/4.jpg'
  f:
    role: 'MIDI研会長'
    name: '9W3R7Y'
    group: 'MIDI研'
    image: 'img/kanbu/5.jpg'

event:
  url: 'https://event.misw.jp/wasedasai2022'
  image: 'https://event.misw.jp/wasedasai2022/img/ogp.png'
